import type { ParticleParams } from '../midi/types';

export type ParticlePreset = {
  id: string;
  name: string;
  blurb: string;
  params: ParticleParams;
};

export const DEFAULT_PARTICLE_PARAMS: ParticleParams = {
  density: 1.1,
  size: 1.15,
  sizeVariance: 0.55,
  speed: 1.05,
  spread: 0.45,
  gravity: 0.55,
  drag: 0.35,
  lifetime: 0.85,
  turbulence: 0.35,
  sparkle: 0.4,
  bloom: 1.15,
  secondaryBurst: 0.55,
  trail: 0.35,
  whiteHot: 0.45,
  swirl: 0.15,
  sustainEmit: 0.35,
  hitFlash: 0.7,
};

export const PARTICLE_PRESETS: ParticlePreset[] = [
  {
    id: 'ember',
    name: 'Ember',
    blurb: 'Warm rising sparks',
    params: {
      density: 1.2,
      size: 1.1,
      sizeVariance: 0.65,
      speed: 0.85,
      spread: 0.35,
      gravity: -0.35,
      drag: 0.4,
      lifetime: 1.15,
      turbulence: 0.55,
      sparkle: 0.5,
      bloom: 1.3,
      secondaryBurst: 0.4,
      trail: 0.45,
      whiteHot: 0.55,
      swirl: 0.2,
      sustainEmit: 0.55,
      hitFlash: 0.85,
    },
  },
  {
    id: 'neon',
    name: 'Neon',
    blurb: 'Electric punchy bursts',
    params: {
      density: 1.35,
      size: 0.95,
      sizeVariance: 0.4,
      speed: 1.45,
      spread: 0.55,
      gravity: 0.15,
      drag: 0.25,
      lifetime: 0.65,
      turbulence: 0.2,
      sparkle: 0.75,
      bloom: 1.55,
      secondaryBurst: 0.9,
      trail: 0.7,
      whiteHot: 0.8,
      swirl: 0.05,
      sustainEmit: 0.25,
      hitFlash: 1,
    },
  },
  {
    id: 'stardust',
    name: 'Stardust',
    blurb: 'Fine glittering dust',
    params: {
      density: 1.6,
      size: 0.55,
      sizeVariance: 0.7,
      speed: 0.55,
      spread: 0.7,
      gravity: 0.2,
      drag: 0.5,
      lifetime: 1.4,
      turbulence: 0.7,
      sparkle: 1,
      bloom: 0.9,
      secondaryBurst: 0.25,
      trail: 0.15,
      whiteHot: 0.65,
      swirl: 0.35,
      sustainEmit: 0.7,
      hitFlash: 0.4,
    },
  },
  {
    id: 'firework',
    name: 'Firework',
    blurb: 'Explosive radial pop',
    params: {
      density: 1.7,
      size: 1.25,
      sizeVariance: 0.5,
      speed: 1.85,
      spread: 1,
      gravity: 0.85,
      drag: 0.2,
      lifetime: 0.95,
      turbulence: 0.15,
      sparkle: 0.6,
      bloom: 1.2,
      secondaryBurst: 1,
      trail: 0.55,
      whiteHot: 0.7,
      swirl: 0,
      sustainEmit: 0.05,
      hitFlash: 1,
    },
  },
  {
    id: 'plasma',
    name: 'Plasma',
    blurb: 'Swirling energy coils',
    params: {
      density: 1.25,
      size: 1.05,
      sizeVariance: 0.45,
      speed: 1.15,
      spread: 0.5,
      gravity: -0.1,
      drag: 0.3,
      lifetime: 1.05,
      turbulence: 0.45,
      sparkle: 0.55,
      bloom: 1.4,
      secondaryBurst: 0.65,
      trail: 0.75,
      whiteHot: 0.5,
      swirl: 0.95,
      sustainEmit: 0.5,
      hitFlash: 0.75,
    },
  },
  {
    id: 'aurora',
    name: 'Aurora',
    blurb: 'Soft floating haze',
    params: {
      density: 0.85,
      size: 1.6,
      sizeVariance: 0.6,
      speed: 0.4,
      spread: 0.6,
      gravity: -0.55,
      drag: 0.55,
      lifetime: 1.7,
      turbulence: 0.4,
      sparkle: 0.25,
      bloom: 1.7,
      secondaryBurst: 0.2,
      trail: 0.2,
      whiteHot: 0.25,
      swirl: 0.25,
      sustainEmit: 0.65,
      hitFlash: 0.35,
    },
  },
  {
    id: 'rain',
    name: 'Spark Rain',
    blurb: 'Falling silver trails',
    params: {
      density: 1.1,
      size: 0.7,
      sizeVariance: 0.35,
      speed: 0.35,
      spread: 0.25,
      gravity: 1.4,
      drag: 0.1,
      lifetime: 0.9,
      turbulence: 0.1,
      sparkle: 0.45,
      bloom: 0.85,
      secondaryBurst: 0.15,
      trail: 0.9,
      whiteHot: 0.55,
      swirl: 0,
      sustainEmit: 0.4,
      hitFlash: 0.3,
    },
  },
  {
    id: 'blizzard',
    name: 'Blizzard',
    blurb: 'Icy flurry chaos',
    params: {
      density: 1.5,
      size: 0.75,
      sizeVariance: 0.8,
      speed: 1.2,
      spread: 0.85,
      gravity: 0.45,
      drag: 0.15,
      lifetime: 1.1,
      turbulence: 0.9,
      sparkle: 0.85,
      bloom: 1,
      secondaryBurst: 0.5,
      trail: 0.4,
      whiteHot: 0.9,
      swirl: 0.55,
      sustainEmit: 0.45,
      hitFlash: 0.55,
    },
  },
  {
    id: 'soft',
    name: 'Soft Glow',
    blurb: 'Subtle elegant light',
    params: {
      density: 0.55,
      size: 1.35,
      sizeVariance: 0.3,
      speed: 0.5,
      spread: 0.3,
      gravity: 0.25,
      drag: 0.5,
      lifetime: 0.7,
      turbulence: 0.15,
      sparkle: 0.15,
      bloom: 1.5,
      secondaryBurst: 0.2,
      trail: 0.1,
      whiteHot: 0.35,
      swirl: 0.05,
      sustainEmit: 0.15,
      hitFlash: 0.45,
    },
  },
  {
    id: 'inferno',
    name: 'Inferno',
    blurb: 'Heavy fire storm',
    params: {
      density: 1.85,
      size: 1.4,
      sizeVariance: 0.7,
      speed: 1.3,
      spread: 0.55,
      gravity: -0.65,
      drag: 0.35,
      lifetime: 1.25,
      turbulence: 0.65,
      sparkle: 0.7,
      bloom: 1.6,
      secondaryBurst: 0.8,
      trail: 0.6,
      whiteHot: 0.75,
      swirl: 0.4,
      sustainEmit: 0.85,
      hitFlash: 1,
    },
  },
  {
    id: 'crystal',
    name: 'Crystal',
    blurb: 'Sharp glass shards',
    params: {
      density: 1.0,
      size: 0.85,
      sizeVariance: 0.25,
      speed: 1.55,
      spread: 0.65,
      gravity: 0.7,
      drag: 0.18,
      lifetime: 0.75,
      turbulence: 0.05,
      sparkle: 0.9,
      bloom: 0.75,
      secondaryBurst: 0.7,
      trail: 0.85,
      whiteHot: 0.95,
      swirl: 0,
      sustainEmit: 0.1,
      hitFlash: 0.9,
    },
  },
  {
    id: 'custom',
    name: 'Custom',
    blurb: 'Your manual mix',
    params: { ...DEFAULT_PARTICLE_PARAMS },
  },
];

export function getPreset(id: string): ParticlePreset {
  return PARTICLE_PRESETS.find((p) => p.id === id) ?? PARTICLE_PRESETS[0];
}
